name: CI for HTML Demo Project

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install project (dummy)
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Success Message
        run: echo "✅ Build successful for HTML demo!"
